version: '3.8'
services:
  mysql_db:
    image: mysql:8.0
    container_name: toko_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toko_db
    ports:
      - "3307:3306"
